### ISSUE TITLE
Restream chat compatibility?

### ISSUE THREAD

**Issue by SpruceMoose001** [gorgarp/TwitchChatPlays#1]
Attempted to use this with restream relaying Youtube Comments into the chat.  Does not work.

I suspect the cause is the chat relay including the username in the text string
so    Spruce:  "W"   is  actually being sent as  "Spruce: W" 

Could be wrong, i'm a code noob.   Basically wanting this to work for simulstreaming between Twitch & Youtube

Tips/Feature update greatly appreciated

**Comment by gorgarp** [comment]
Done. Please review the updated readme.
